#!/bin/bash

export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_WAYLAND_FORCE_DPI=96
export QUTE_SKIP_WAYLAND_CHECK=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_QPA_PLATFORM=wayland

#export XDG_CURRENT_DESKTOP=Unity

export ELM_DISPLAY=wl
export ECORE_EVAS_ENGINE=wayland_egl

#export GDK_BACKEND=wayland
#export CLUTTER_BACKEND=wayland

export SDL_VIDEODRIVER=wayland

export _JAVA_AWT_WM_NONREPARENTING=1

export PATH=$PATH:$HOME/bin

mv .wsession-errors .wsession-errors.prev
exec sway 2> .wsession-errors
